/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#38485d',
        'on-background': '#191c1e',
        'inverse-surface': '#2d3133',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#6dfe9c',
        'outline': '#757682',
        'secondary': '#505f76',
        'surface-container-low': '#f2f4f6',
        'tertiary-fixed-dim': '#4de082',
        'tertiary': '#003215',
        'secondary-fixed-dim': '#b7c8e1',
        'on-primary': '#ffffff',
        'on-surface': '#191c1e',
        'background': '#f7f9fb',
        'on-primary-fixed': '#00164e',
        'surface-container-high': '#e6e8ea',
        'secondary-fixed': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f7f9fb',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#005227',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-container': '#27c56a',
        'surface-tint': '#4059aa',
        'surface': '#f7f9fb',
        'primary-fixed-dim': '#b6c4ff',
        'primary-fixed': '#dce1ff',
        'inverse-primary': '#b6c4ff',
        'on-secondary-container': '#54647a',
        'outline-variant': '#c5c5d3',
        'surface-dim': '#d8dadc',
        'on-tertiary': '#ffffff',
        'primary-container': '#1e3a8a',
        'on-tertiary-fixed': '#00210c',
        'on-primary-fixed-variant': '#264191',
        'surface-variant': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'on-primary-container': '#90a8ff',
        'tertiary-container': '#004b23',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#0b1c30',
        'secondary-container': '#d0e1fb',
        'primary': '#00236f',
        'surface-container': '#eceef0',
        'on-surface-variant': '#444651',
        'error': '#ba1a1a',
        'success': '#10b981',
        'on-success': '#ffffff',
        'success-container': '#d1fae5',
        'on-success-container': '#065f46',
        'mpesa-green': '#26B21A',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        gutter: '24px',
        sidebar_width: '240px',
        sm: '8px',
        xl: '32px',
        '2xl': '48px',
        unit: '4px',
        xs: '4px',
        lg: '24px',
        sidebar_collapsed: '72px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '30px', fontWeight: '700' }],
        'title-md': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'title-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'currency': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.07), 0 1px 2px rgba(0,0,0,0.05)',
        'card-hover': '0 8px 24px rgba(0,0,0,0.10)',
        overlay: '0 24px 64px rgba(0,0,0,0.18)',
        'inner-sm': 'inset 0 1px 3px rgba(0,0,0,0.06)',
        'glow-primary': '0 0 0 3px rgba(0,35,111,0.12)',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0', transform: 'translateY(4px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(12px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.96) translateY(4px)' }, to: { opacity: '1', transform: 'scale(1) translateY(0)' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
      },
      animation: {
        'fade-in': 'fadeIn 0.25s ease-out both',
        'slide-up': 'slideUp 0.3s cubic-bezier(0.16,1,0.3,1) both',
        'scale-in': 'scaleIn 0.2s cubic-bezier(0.16,1,0.3,1) both',
        'slide-in-right': 'slideInRight 0.3s cubic-bezier(0.16,1,0.3,1) both',
        shimmer: 'shimmer 2s linear infinite',
      },
    },
  },
  plugins: [],
};
