/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error-container': '#93000a',
        'on-secondary-fixed-variant': '#38485d',
        'on-background': '#191c1e',
        'inverse-surface': '#2d3133',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#6dfe9c',
        'outline': '#757682',
        'secondary': '#505f76',
        'surface-container-low': '#f2f4f6',
        'tertiary-fixed-dim': '#4de082',
        'tertiary': '#003215',
        'secondary-fixed-dim': '#b7c8e1',
        'on-primary': '#ffffff',
        'on-surface': '#191c1e',
        'background': '#f7f9fb',
        'on-primary-fixed': '#00164e',
        'surface-container-high': '#e6e8ea',
        'secondary-fixed': '#d3e4fe',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f7f9fb',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#005227',
        'surface-container-highest': '#e0e3e5',
        'on-tertiary-container': '#27c56a',
        'surface-tint': '#4059aa',
        'surface': '#f7f9fb',
        'primary-fixed-dim': '#b6c4ff',
        'primary-fixed': '#dce1ff',
        'inverse-primary': '#b6c4ff',
        'on-secondary-container': '#54647a',
        'outline-variant': '#c5c5d3',
        'surface-dim': '#d8dadc',
        'on-tertiary': '#ffffff',
        'primary-container': '#1e3a8a',
        'on-tertiary-fixed': '#00210c',
        'on-primary-fixed-variant': '#264191',
        'surface-variant': '#e0e3e5',
        'inverse-on-surface': '#eff1f3',
        'on-primary-container': '#90a8ff',
        'tertiary-container': '#004b23',
        'error-container': '#ffdad6',
        'on-secondary-fixed': '#0b1c30',
        'secondary-container': '#d0e1fb',
        'primary': '#00236f',
        'surface-container': '#eceef0',
        'on-surface-variant': '#444651',
        'error': '#ba1a1a',
        'mpesa-green': '#26B21A',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        gutter: '20px',
        sidebar_width: '260px',
        sm: '8px',
        xl: '32px',
        unit: '4px',
        xs: '4px',
        lg: '24px',
        sidebar_collapsed: '72px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'currency': ['24px', { lineHeight: '32px', fontWeight: '700' }],
      },
      boxShadow: {
        card: '0px 1px 3px rgba(0,0,0,0.1), 0px 1px 2px rgba(0,0,0,0.06)',
        'card-hover': '0px 10px 15px -3px rgba(0,0,0,0.1), 0px 4px 6px -2px rgba(0,0,0,0.05)',
        overlay: '0px 20px 25px -5px rgba(0,0,0,0.1)',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideIn: { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
        pulse2: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
      },
      animation: {
        'fade-in': 'fadeIn 0.3s ease-out',
        'slide-in': 'slideIn 0.3s ease-out',
      },
    },
  },
  plugins: [],
};
